sonar.projectKey=jalantechnologies_flask-react-template
sonar.projectVersion=1.0

# Tests
sonar.tests=tests/
sonar.test.exclusions=tests/**/*

# Coverage
sonar.python.coverage.reportPaths=output/coverage.xml

# Modules
sonar.modules=backend,frontend

# Backend module
backend.sonar.projectName=Backend
backend.sonar.projectBaseDir=src/apps/backend
backend.sonar.sources=.
backend.sonar.python.version=3.11

# Frontend module
frontend.sonar.projectName=Frontend
frontend.sonar.projectBaseDir=src/apps/frontend
frontend.sonar.sources=.
frontend.sonar.coverage.exclusions=**/*
